//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LeagueOfLegends.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChampionStat
    {
        public double hp { get; set; }
        public double hpPerLevel { get; set; }
        public double mp { get; set; }
        public double mpPerLevel { get; set; }
        public double moveSpeed { get; set; }
        public double armor { get; set; }
        public double armorPerLevel { get; set; }
        public double spellBlock { get; set; }
        public double spellBlockPerLevel { get; set; }
        public double attackRange { get; set; }
        public double hpRegen { get; set; }
        public double hpRegenPerLevel { get; set; }
        public double mpRegen { get; set; }
        public double mpRegenPerLevel { get; set; }
        public double crit { get; set; }
        public double critPerLevel { get; set; }
        public double attackDamage { get; set; }
        public double attackDamagePerLevel { get; set; }
        public double attackSpeed { get; set; }
        public double attackSpeedPerLevel { get; set; }
        public string idChampion { get; set; }
    
        public virtual Champion Champion { get; set; }
    }
}
