//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LeagueOfLegends.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChampionInfo
    {
        public string idChampion { get; set; }
        public byte attack { get; set; }
        public byte defense { get; set; }
        public byte magic { get; set; }
        public byte difficulty { get; set; }
    
        public virtual Champion Champion { get; set; }
    }
}
