//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LeagueOfLegends.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Champion_Tag
    {
        public string idChampion { get; set; }
        public byte idTag { get; set; }
        public int id { get; set; }
    
        public virtual Champion Champion { get; set; }
        public virtual Tag Tag { get; set; }
    }
}
