//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LeagueOfLegends.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class LeagueOfLegendsEntities : DbContext
    {
        public LeagueOfLegendsEntities()
            : base("name=LeagueOfLegendsEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Champion> Champions { get; set; }
        public virtual DbSet<ChampionInfo> ChampionInfoes { get; set; }
        public virtual DbSet<ChampionStat> ChampionStats { get; set; }
        public virtual DbSet<Passive> Passives { get; set; }
        public virtual DbSet<Spell> Spells { get; set; }
        public virtual DbSet<Tag> Tags { get; set; }
        public virtual DbSet<Tip> Tips { get; set; }
    }
}
