//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LeagueOfLegends.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Spell
    {
        public string id { get; set; }
        public string name { get; set; }
        public string description { get; set; }
        public byte maxRank { get; set; }
        public string image { get; set; }
        public string idChampion { get; set; }
    
        public virtual Champion Champion { get; set; }
    }
}
